development:
  clients:
    default:
      database: api_rider_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
test:
  clients:
    default:
      database: api_rider_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
default:
  clients:
      default:
        database: api_rider
        hosts:
          - localhost:27017
        options:
          server_selection_timeout: 1
