development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      options:
        server_selection_timeout: 1
default:
  clients:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      options:
        server_selection_timeout: 1
